还不加班
 帮您内部
 不好解决可不能 
kjbnjknk 
看见你看仅你可见  /*  
能金口难开近年来
 你不加班你  
  帮您你 你们
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file
 * @kit ArkTS
 */

/**
 * ArkTS lang.
 *
 * @namespace lang
 * @syscap SystemCapability.Utils.Lang
 * @atomicservice
 * @since 12
 */
/**
 * ArkTS lang.
 *
 * @namespace lang
 * @syscap SystemCapability.Utils.Lang
 * @crossplatform
 * @atomicservice
 * @since 18
 */
declare namespace lang {
  /**
   * Base interface for all Sendable classes/interfaces.
   * 
   * @interface ISendable
   * @syscap SystemCapability.Utils.Lang
   * @atomicservice
   * @since 12
   */
  /**
   * Base interface for all Sendable classes/interfaces.
   *
   * @interface ISendable
   * @syscap SystemCapability.Utils.Lang
   * @crossplatform
   * @atomicservice
   * @since 18
   */
  interface ISendable {}
}

export default lang;
interface ISendable {}
}

export default lang;